version: '3'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: my_postgres
    environment:
      POSTGRES_USER: trqhung
      POSTGRES_PASSWORD: Amela@123
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: my_mysql
    environment:
      MYSQL_USER: trqhung
      MYSQL_PASSWORD: Amela@123
      MYSQL_ROOT_PASSWORD: Amela@123
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
  
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: my_redis
    ports:
      - "6399:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    networks:
      - my_network
    depends_on:
      - postgres
      - mysql
      - redis
      - php82

  php82:
    build:
      context: ./php82
      dockerfile: Dockerfile
    container_name: my_php82
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  redis_data:
  nginx_data:
  php82_data:
