version: '3'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: my_postgres
    environment:
      POSTGRES_USER: trqhung
      POSTGRES_PASSWORD: Amela@123
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: my_mysql
    environment:
      MYSQL_USER: trqhung
      MYSQL_PASSWORD: Amela@123
      MYSQL_ROOT_PASSWORD: Amela@123
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
